name: Bad CI/CD

on:
  push:
    branches:
      - main
      - lab-3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Add test placeholder
        run: |
          mkdir -p tests
          echo "def test_placeholder(): assert True" > tests/test_placeholder.py

      - name: Run tests
        run: |
          pip install pytest
          pytest tests/

      - name: Build and deploy
        run: |
          echo "Building application..."
          mkdir dist
          cp -r src/* dist/
          echo "Deploying application..."
          echo "Deployed successfully!"