name: Good CI/CD

on:
  push:
    branches:
      - main
      - lab-3

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/ --maxfail=1

      - name: Build application
        run: |
          echo "Building application..."
          mkdir -p dist
          cp -r src/* dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-application
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-application

      - name: Deploy application
        run: |
          echo "Deploying application..."
          echo "Deployed successfully!"
