name: Good CI/CD

on:
  push:
    branches:
      - main
      - lab-3

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Add test placeholder
        run: |
          mkdir -p tests
          echo "def test_placeholder(): assert True" > tests/test_placeholder.py

      - name: Run tests
        run: |
          pip install pytest
          pytest tests/ --maxfail=1

      - name: Add source placeholder
        run: |
          mkdir -p src
          echo "print('Hello, World!')" > src/main.py

      - name: Build application
        run: |
          echo "Building application..."
          mkdir -p dist
          if [ -d "src" ]; then
            cp -r src/* dist/
          else
            echo "Warning: 'src/' directory not found. Skipping copy step."
          fi

      - name: Deploy application
        run: |
          echo "Deploying application..."
          echo "Deployed successfully!"
